# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZrJC32fbJz33KU6nx_EBoyBTAieBV8o
"""

!pip install supabase
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from supabase import create_client
import joblib
import os
from typing import Any, Dict, List, Optional

# --------------- FastAPI app --------------- instantly

app = FastAPI(title="Fantasy Backend API")

# --------------- Supabase setup ---------------

SUPABASE_URL = "https://octfocmufcukbfhaepjf.supabase.co"
SUPABASE_KEY = "sb_publishable_5mYG0HDrdEZD0hFZIk-zyg_BarGoaZy"

if not SUPABASE_URL or not SUPABASE_KEY:
    raise RuntimeError("SUPABASE_URL and SUPABASE_KEY must be set as environment variables.")

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

# --------------- Load models ---------------

models: Dict[str, Dict[str, Any]] = {
    "QB": {
        "rookie": joblib.load("qb_rookie.pkl"),
        "veteran": joblib.load("qb_veteran.pkl"),
    },
    "RB": {
        "rookie": joblib.load("rb_rookie.pkl"),
        "veteran": joblib.load("rb_veteran.pkl"),
    },
    "WR": {
        "rookie": joblib.load("wr_rookie.pkl"),
        "veteran": joblib.load("wr_veteran.pkl"),
    },
    "TE": {
        "rookie": joblib.load("te_rookie.pkl"),
        "veteran": joblib.load("te_veteran.pkl"),
    },
}

# --------------- Request/response models ---------------

class PredictionRequest(BaseModel):
    player_id: str
    week: int
    user_id: Optional[str] = None  # optional, for caching per user

class PredictionResponse(BaseModel):
    player_id: str
    week: int
    prediction: float

# --------------- Helpers: Supabase ---------------

def get_player_by_id(player_id: str) -> Dict[str, Any]:
    """Fetch a single player record from Supabase."""
    resp = (
        supabase
        .table("players")
        .select("*")
        .eq("id", player_id)
        .execute()
    )

    if not resp.data:
        raise HTTPException(status_code=404, detail=f"Player with id {player_id} not found.")

    # Assuming `id` is unique, take the first row
    return resp.data[0]

# --------------- Helpers: feature builders ---------------
# These are the functions you customize to match how each model was trained.
# Right now they are stubs with examples; you should replace the contents
# with the actual fields / transformations you used in training.

def build_qb_rookie_features(player: Dict[str, Any], week: int) -> List[float]:
    """
    Build feature vector for QB rookie model.
    Replace the contents with the exact stats/features you trained on.
    """
    # EXAMPLE ONLY — change to your real features:
    features = [
        player.get("college_efficiency", 0.0),
        player.get("draft_capital", 0.0),
        player.get("rush_share", 0.0),
        player.get("team_pass_rate", 0.0),
        week,  # sometimes week is a feature
    ]
    return features

def build_qb_veteran_features(player: Dict[str, Any], week: int) -> List[float]:
    """Build feature vector for QB veteran model."""
    features = [
        player.get("prev_pass_attempts", 0.0),
        player.get("prev_pass_yards", 0.0),
        player.get("prev_rush_yards", 0.0),
        player.get("td_rate", 0.0),
        player.get("int_rate", 0.0),
        week,
    ]
    return features

def build_rb_rookie_features(player: Dict[str, Any], week: int) -> List[float]:
    """Build feature vector for RB rookie model."""
    features = [
        player.get("college_yards_per_route", 0.0),
        player.get("draft_capital", 0.0),
        player.get("team_rush_rate", 0.0),
        week,
    ]
    return features

def build_rb_veteran_features(player: Dict[str, Any], week: int) -> List[float]:
    """Build feature vector for RB veteran model."""
    features = [
        player.get("prev_rush_attempts", 0.0),
        player.get("prev_rush_yards", 0.0),
        player.get("prev_targets", 0.0),
        player.get("redzone_touches", 0.0),
        week,
    ]
    return features

def build_wr_rookie_features(player: Dict[str, Any], week: int) -> List[float]:
    """Build feature vector for WR rookie model."""
    features = [
        player.get("college_target_share", 0.0),
        player.get("college_aDOT", 0.0),
        player.get("draft_capital", 0.0),
        week,
    ]
    return features

def build_wr_veteran_features(player: Dict[str, Any], week: int) -> List[float]:
    """Build feature vector for WR veteran model."""
    features = [
        player.get("prev_targets", 0.0),
        player.get("prev_rec_yards", 0.0),
        player.get("prev_tds", 0.0),
        week,
    ]
    return features

def build_te_rookie_features(player: Dict[str, Any], week: int) -> List[float]:
    """Build feature vector for TE rookie model."""
    features = [
        player.get("college_target_share", 0.0),
        player.get("draft_capital", 0.0),
        week,
    ]
    return features

def build_te_veteran_features(player: Dict[str, Any], week: int) -> List[float]:
    """Build feature vector for TE veteran model."""
    features = [
        player.get("prev_targets", 0.0),
        player.get("prev_rec_yards", 0.0),
        player.get("redzone_targets", 0.0),
        week,
    ]
    return features

# Mapping so we don't write a giant if/else block
FEATURE_BUILDERS = {
    ("QB", True): build_qb_rookie_features,
    ("QB", False): build_qb_veteran_features,
    ("RB", True): build_rb_rookie_features,
    ("RB", False): build_rb_veteran_features,
    ("WR", True): build_wr_rookie_features,
    ("WR", False): build_wr_veteran_features,
    ("TE", True): build_te_rookie_features,
    ("TE", False): build_te_veteran_features,
}

# --------------- Core prediction helper ---------------

def predict_for_player_and_week(player: Dict[str, Any], week: int) -> float:
    """
    Decide rookie/vet based on years_of_experience,
    pick the correct model, build the correct features, and predict.
    """
    position = player.get("position")
    if position not in models:
        raise HTTPException(status_code=400, detail=f"Unsupported position: {position}")

    years = player.get("years_of_experience")
    if years is None:
        raise HTTPException(status_code=400, detail="Player missing years_of_experience field.")

    is_rookie = (years == 0)
    model_type = "rookie" if is_rookie else "veteran"

    feature_builder = FEATURE_BUILDERS.get((position, is_rookie))
    if feature_builder is None:
        raise HTTPException(status_code=400, detail=f"No feature builder for {position}, rookie={is_rookie}")

    features = feature_builder(player, week)
    model = models[position][model_type]

    # Most sklearn-like models want a 2D array: [features]
    prediction = model.predict([features])[0]
    # Ensure we return a plain float
    return float(prediction)

# --------------- API endpoints ---------------

@app.get("/")
def root():
    return {"message": "Fantasy backend is running."}

@app.get("/players")
def get_players():
    """
    Return all players. Use filters on the frontend to build dropdowns/search.
    """
    resp = supabase.table("players").select("*").execute()
    return resp.data

@app.get("/preseason")
def preseason_rankings():
    """
    Return preseason rankings from the players table,
    ordered by preseason_rank ascending.
    """
    resp = (
        supabase
        .table("players")
        .select("id, name, position, team, preseason_rank, preseason_pts, preseason_tier")
        .order("preseason_rank", asc=True)
        .execute()
    )
    return resp.data

@app.post("/predict", response_model=PredictionResponse)
def predict(req: PredictionRequest):
    """
    Predict fantasy points for a given player and week.
    - Uses player_id to look up the player in Supabase
    - Determines rookie/veteran based on years_of_experience == 0
    - Chooses the correct model (position + rookie/vet)
    - Builds model-specific features
    - Returns a single numeric prediction
    - Optionally caches to Supabase if user_id is provided
    """
    player = get_player_by_id(req.player_id)
    prediction_value = predict_for_player_and_week(player, req.week)

    # Optional: cache in Supabase
    if req.user_id:
        supabase.table("cached_predictions").insert({
            "user_id": req.user_id,
            "player_id": req.player_id,
            "week": req.week,
            "prediction": prediction_value,
        }).execute()

    return PredictionResponse(
        player_id=req.player_id,
        week=req.week,
        prediction=prediction_value,
    )

